version: 2

# Explicitly set the OS and Python versions
build:
  os: "ubuntu-24.04"
  tools:
    nodejs: "20"
    python: "3.12"

    # Explicitly set the version of Python and its requirements
python:
  install:
    - requirements: docs/requirements.txt
